services:
  mes-api:
    build:
      context: .
      dockerfile: MES.API/Dockerfile
    container_name: mes-api
    restart: always
    # Menambahkan DNS Google agar container bisa mengenali alamat Neon DB (Host luar)
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5096:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mes-web:
    build:
      context: .
      dockerfile: MES.Web/Dockerfile
    container_name: mes-web
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiSettings__BaseUrl=http://mes-api:8080
    depends_on:
      - mes-api
